/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/curated/copasi": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Use the tool copasi. */
        post: operations["run-copasi"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/curated/tellurium": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Use the tool tellurium. */
        post: operations["run-tellurium"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/simulation/run": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Run a simulation
         * @description `simulator` names an owner-published image this deployment lists (settings.prebuilt_simulators);
         *     the job then runs in that image instead of the shared container. Omitted: the shared container.
         */
        post: operations["run-simulation"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/simulations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List simulations, newest first, each with its latest SLURM job */
        get: operations["list-simulations"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/simulations/{simulation_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Describe one simulation: its latest SLURM job, and how many events and datasets its run recorded */
        get: operations["get-simulation"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/results/simulations/status/batch": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get simulation status records for a list of IDs */
        get: operations["get-simulations-status-batch"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/results/simulation/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get the simulation status record by its ID */
        get: operations["get-simulation-status"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/results/simulation/results/file": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get simulation results as a zip file */
        get: operations["get-simulation-results-file"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/results/simulator/build/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get the simulator build status record by its ID */
        get: operations["get-simulator-build-status"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/results/simulation/events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get a page of a simulation's events, in the order they were recorded */
        get: operations["get-simulation-events"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/results/simulation/trace": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get a simulation's spans as a tree, each span with its own events */
        get: operations["get-simulation-trace"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/results/simulation/trace/chrome": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get a simulation's trace as a Chrome Trace Event document (open it in ui.perfetto.dev) */
        get: operations["get-simulation-trace-chrome"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/core/simulator/list": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get the list of simulators */
        get: operations["get-simulator-list"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/core/processes/list": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get the list of processes */
        get: operations["get-processes-list"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/core/steps/list": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get the list of processes */
        get: operations["get-steps-list"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/datasets": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List the datasets runs advertised, newest simulations first */
        get: operations["list-datasets"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/datasets/{dataset_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Describe one dataset */
        get: operations["get-dataset"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/datasets/{dataset_id}/content": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Read a dataset's file (supports HTTP Range requests) */
        get: operations["get-dataset-content"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Check Health */
        get: operations["check_health_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/version": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Version */
        get: operations["get_version_version_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * BiGraphComputeType
         * @enum {string}
         */
        BiGraphComputeType: "process" | "step";
        /** BiGraphProcess */
        BiGraphProcess: {
            /** Module */
            module: string;
            /** Name */
            name: string;
            compute_type: components["schemas"]["BiGraphComputeType"];
            /** Inputs */
            inputs: string;
            /** Outputs */
            outputs: string;
            /** Database Id */
            database_id: number;
        };
        /** BiGraphStep */
        BiGraphStep: {
            /** Module */
            module: string;
            /** Name */
            name: string;
            compute_type: components["schemas"]["BiGraphComputeType"];
            /** Inputs */
            inputs: string;
            /** Outputs */
            outputs: string;
            /** Database Id */
            database_id: number;
        };
        /** Body_run-copasi */
        "Body_run-copasi": {
            /**
             * Sbml
             * Format: binary
             */
            sbml: string;
        };
        /** Body_run-simulation */
        "Body_run-simulation": {
            /**
             * Uploaded File
             * Format: binary
             */
            uploaded_file: string;
        };
        /** Body_run-tellurium */
        "Body_run-tellurium": {
            /**
             * Sbml
             * Format: binary
             */
            sbml: string;
        };
        /**
         * ContainerizationEngine
         * @enum {integer}
         */
        ContainerizationEngine: 0 | 1 | 2 | 3;
        /** ContainerizationFileRepr */
        ContainerizationFileRepr: {
            /** Representation */
            representation: string;
            containerization_engine: components["schemas"]["ContainerizationEngine"];
        };
        /**
         * Dataset
         * @description A file a run produced, readable by anyone who may read its simulation (O7).
         */
        Dataset: {
            /** Id */
            id: string;
            /** Simulation Id */
            simulation_id: number;
            /** Path */
            path: string;
            /** Kind */
            kind: string;
            /** Media Type */
            media_type: string;
            /** Display Name */
            display_name: string;
            /** Size Bytes */
            size_bytes?: number | null;
            /** Sha256 */
            sha256?: string | null;
            /** Attributes */
            attributes?: {
                [key: string]: unknown;
            };
            /** Origin */
            origin: string;
            /** Span Id */
            span_id?: string | null;
            /**
             * Available
             * @default true
             */
            available: boolean;
            /** Created At */
            created_at?: string | null;
            /** Updated At */
            updated_at?: string | null;
        };
        /** DatasetPage */
        DatasetPage: {
            /** Datasets */
            datasets: components["schemas"]["Dataset"][];
            /** Total */
            total: number;
            /** Next Offset */
            next_offset?: number | null;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** HpcRun */
        HpcRun: {
            /** Database Id */
            database_id: number;
            /** Slurmjobid */
            slurmjobid: number;
            /** Correlation Id */
            correlation_id: string;
            job_type: components["schemas"]["JobType"];
            /** Sim Id */
            sim_id: number | null;
            /** Simulator Id */
            simulator_id: number | null;
            status?: components["schemas"]["JobStatus"] | null;
            /** Start Time */
            start_time?: string | null;
            /** End Time */
            end_time?: string | null;
            /** Error Message */
            error_message?: string | null;
            /** Trace Id */
            trace_id?: string | null;
        };
        /**
         * JobStatus
         * @enum {string}
         */
        JobStatus: "waiting" | "queued" | "running" | "completed" | "failed" | "pending" | "cancelled" | "out_of_memory" | "suspended" | "timeout" | "unknown";
        /**
         * JobType
         * @enum {string}
         */
        JobType: "simulation" | "build_container";
        /**
         * PackageType
         * @enum {string}
         */
        PackageType: "pypi" | "conda";
        /** RegisteredPackage */
        RegisteredPackage: {
            /** Database Id */
            database_id: number;
            package_type: components["schemas"]["PackageType"];
            /** Name */
            name: string;
            /** Processes */
            processes: components["schemas"]["BiGraphProcess"][];
            /** Steps */
            steps: components["schemas"]["BiGraphStep"][];
        };
        /** RegisteredSimulators */
        RegisteredSimulators: {
            /** Versions */
            versions: components["schemas"]["SimulatorVersion"][];
            /** Timestamp */
            timestamp?: string | null;
        };
        /**
         * RunEvent
         * @description One structured event of a run, from the API, the job script or the simulator's engine.
         */
        RunEvent: {
            /** Cursor */
            cursor?: number | null;
            /** Seq */
            seq: number;
            /** Source */
            source: string;
            /** Ts */
            ts: string;
            /** Component */
            component: string;
            /** Event */
            event: string;
            /**
             * Level
             * @default info
             */
            level: string;
            /** Baggage */
            baggage?: {
                [key: string]: unknown;
            } | null;
            /** Global Time */
            global_time?: number | null;
            /** Wall Time */
            wall_time?: number | null;
            /** Span Id */
            span_id?: string | null;
            /** Parent Span Id */
            parent_span_id?: string | null;
            /** Payload */
            payload?: {
                [key: string]: unknown;
            } | null;
            /** Tags */
            tags?: {
                [key: string]: unknown;
            } | null;
        };
        /**
         * RunEventPage
         * @description A page of a simulation's events, in the order they were recorded.
         *
         *     ``next_cursor`` is the ``after`` for the next page, None at the end.
         */
        RunEventPage: {
            /** Simulation Id */
            simulation_id: number;
            /** Trace Id */
            trace_id: string | null;
            /** Events */
            events: components["schemas"]["RunEvent"][];
            /** Next Cursor */
            next_cursor?: number | null;
        };
        /**
         * RunSpan
         * @description A node of a run's trace tree, folded from ``span.start`` / ``span.end`` events. ``end_ts`` is None while open.
         */
        RunSpan: {
            /** Span Id */
            span_id: string;
            /** Parent Span Id */
            parent_span_id?: string | null;
            /** Name */
            name: string;
            /** Attrs */
            attrs?: {
                [key: string]: unknown;
            } | null;
            /** Start Ts */
            start_ts?: string | null;
            /** End Ts */
            end_ts?: string | null;
            /** Duration S */
            duration_s?: number | null;
            /** Status */
            status?: string | null;
            /** Error */
            error?: string | null;
        };
        /**
         * RunTraceTree
         * @description A simulation's spans as a forest, each span carrying its own events.
         */
        RunTraceTree: {
            /** Simulation Id */
            simulation_id: number;
            /** Trace Id */
            trace_id: string | null;
            /** Roots */
            roots: components["schemas"]["SpanTree"][];
        };
        /**
         * SimulationDetail
         * @description A simulation with what its run recorded.
         */
        SimulationDetail: {
            /** Simulation Id */
            simulation_id: number;
            /** Created At */
            created_at?: string | null;
            /** Experiment Id */
            experiment_id: string;
            /** Simulator Id */
            simulator_id: number;
            /** Simulator */
            simulator?: string | null;
            /** Container Def Hash */
            container_def_hash: string;
            /** @default public */
            visibility: components["schemas"]["Visibility"];
            /** Status */
            status: string;
            /** Slurm Job Id */
            slurm_job_id?: number | null;
            /** Start Time */
            start_time?: string | null;
            /** End Time */
            end_time?: string | null;
            /** Exit Code */
            exit_code?: number | null;
            /** Error Message */
            error_message?: string | null;
            /** Trace Id */
            trace_id?: string | null;
            /**
             * Event Count
             * @default 0
             */
            event_count: number;
            /**
             * Dataset Count
             * @default 0
             */
            dataset_count: number;
        };
        /** SimulationExperiment */
        SimulationExperiment: {
            /** Simulation Database Id */
            simulation_database_id: number;
            /** Simulator Database Id */
            simulator_database_id: number;
            /** Last Updated */
            last_updated?: string;
            /** Metadata */
            metadata?: {
                [key: string]: string;
            };
        };
        /** SimulationPage */
        SimulationPage: {
            /** Simulations */
            simulations: components["schemas"]["SimulationSummary"][];
            /** Total */
            total: number;
            /** Next Offset */
            next_offset?: number | null;
        };
        /**
         * SimulationSummary
         * @description One simulation as a listing shows it: what ran, where, and how it went (its latest SLURM job).
         */
        SimulationSummary: {
            /** Simulation Id */
            simulation_id: number;
            /** Created At */
            created_at?: string | null;
            /** Experiment Id */
            experiment_id: string;
            /** Simulator Id */
            simulator_id: number;
            /** Simulator */
            simulator?: string | null;
            /** Container Def Hash */
            container_def_hash: string;
            /** @default public */
            visibility: components["schemas"]["Visibility"];
            /** Status */
            status: string;
            /** Slurm Job Id */
            slurm_job_id?: number | null;
            /** Start Time */
            start_time?: string | null;
            /** End Time */
            end_time?: string | null;
            /** Exit Code */
            exit_code?: number | null;
            /** Error Message */
            error_message?: string | null;
            /** Trace Id */
            trace_id?: string | null;
        };
        /** SimulatorVersion */
        SimulatorVersion: {
            container_def: components["schemas"]["ContainerizationFileRepr"];
            /** Container Def Hash */
            container_def_hash: string;
            /** Packages */
            packages: components["schemas"]["RegisteredPackage"][] | null;
            /** Database Id */
            database_id: number;
            /** Created At */
            created_at?: string | null;
        };
        /**
         * SpanTree
         * @description A span with its own events (those whose ``span_id`` is the span's) and its children, by start time.
         */
        SpanTree: {
            span: components["schemas"]["RunSpan"];
            /** Events */
            events?: components["schemas"]["RunEvent"][];
            /** Children */
            children?: components["schemas"]["SpanTree"][];
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
        /**
         * Visibility
         * @description Who may read a simulation and everything it produced (plan-observability O7).
         * @enum {string}
         */
        Visibility: "public" | "private";
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    "run-copasi": {
        parameters: {
            query: {
                start_time: number;
                duration: number;
                num_data_points: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_run-copasi"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SimulationExperiment"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    "run-tellurium": {
        parameters: {
            query: {
                start_time: number;
                end_time: number;
                num_data_points: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_run-tellurium"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SimulationExperiment"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    "run-simulation": {
        parameters: {
            query?: {
                interval_time?: number;
                batch_submission?: boolean;
                simulator?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_run-simulation"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SimulationExperiment"];
                };
            };
            /** @description The submission cannot run. For a problem with the request itself (empty file, unsupported type, interval out of range) `detail` is a string. For a problem with its contents (unreadable archive, or processes the registry does not allow) `detail` is an object with a `message` and a `violations` list naming each address. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    "list-simulations": {
        parameters: {
            query?: {
                /** @description Only simulations in this state */
                status?: ("submitting" | "waiting" | "queued" | "pending" | "running" | "completed" | "failed" | "cancelled" | "out_of_memory" | "suspended" | "timeout" | "unknown") | null;
                /** @description Only this prebuilt simulator (by name), or container definitions with this hash prefix */
                simulator?: string | null;
                /** @description Only simulations created at or after this time */
                since?: string | null;
                limit?: number;
                offset?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SimulationPage"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    "get-simulation": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                simulation_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SimulationDetail"];
                };
            };
            /** @description The simulation does not exist, or the caller may not read it */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    "get-simulations-status-batch": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": number[];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HpcRun"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    "get-simulation-status": {
        parameters: {
            query: {
                simulation_id: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HpcRun"];
                };
            };
            /** @description The requested resource does not exist */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    "get-simulation-results-file": {
        parameters: {
            query: {
                simulation_id: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Simulation result zip file */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/octet-stream": unknown;
                };
            };
            /** @description The simulation does not exist, or its results are not available */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    "get-simulator-build-status": {
        parameters: {
            query: {
                simulator_id: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HpcRun"];
                };
            };
            /** @description The requested resource does not exist */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    "get-simulation-events": {
        parameters: {
            query: {
                /** @description Return events after this cursor (a previous page's next) */
                after?: number | null;
                limit?: number;
                /** @description Only events at this level (debug, info, warning, error) */
                level?: string | null;
                /** @description Only events with this name, e.g. job.end */
                event?: string | null;
                /** @description Only events inside this span */
                span_id?: string | null;
                simulation_id: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RunEventPage"];
                };
            };
            /** @description The requested resource does not exist */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    "get-simulation-trace": {
        parameters: {
            query: {
                simulation_id: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RunTraceTree"];
                };
            };
            /** @description The requested resource does not exist */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    "get-simulation-trace-chrome": {
        parameters: {
            query: {
                simulation_id: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description The requested resource does not exist */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    "get-simulator-list": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RegisteredSimulators"];
                };
            };
        };
    };
    "get-processes-list": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BiGraphProcess"][];
                };
            };
        };
    };
    "get-steps-list": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BiGraphStep"][];
                };
            };
        };
    };
    "list-datasets": {
        parameters: {
            query?: {
                /** @description Only this simulation's datasets */
                simulation_id?: number | null;
                /** @description Only this kind, e.g. results, table, figure, archive */
                kind?: string | null;
                /** @description Only datasets whose path or name contains this */
                q?: string | null;
                /** @description Only files that still exist (false: only missing) */
                available?: boolean | null;
                limit?: number;
                offset?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DatasetPage"];
                };
            };
            /** @description The simulation does not exist, or the caller may not read it */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    "get-dataset": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                dataset_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Dataset"];
                };
            };
            /** @description The dataset does not exist, or the caller may not read it */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    "get-dataset-content": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                dataset_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The file */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/octet-stream": unknown;
                };
            };
            /** @description The dataset does not exist, the caller may not read it, or its file is gone */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    check_health_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
    get_version_version_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": string;
                };
            };
        };
    };
}
