"""Bring every wrapper in the vivarium-collective catalog into the registry at level `listed`.

Strategy decision 5, phase A: "every wrapper appears at *listed*". The catalog (`viva-catalog`) is a discovery list
of repositories; this pins each one to the commit its branch points at today and writes the result to
`catalog.yaml`, next to the hand-maintained `manifest.yaml`. It only reads from GitHub.

Run it, review the diff, and commit it by pull request:

    uv run python -m compose_api.registry.catalog

Set GITHUB_TOKEN to avoid the unauthenticated API rate limit. An entry that should rise above `listed` moves into
`manifest.yaml` with its evidence; an entry there takes precedence over the same id here.
"""

import datetime
import os
import sys
from pathlib import Path
from typing import Any

import httpx
import yaml
from pydantic import BaseModel

from compose_api.registry.manifest import CATALOG_PATH, CurationLevel, RegistryEntry

CATALOG_URL = "https://raw.githubusercontent.com/vivarium-collective/viva-catalog/main/viva_marketplace/modules.json"
_HEADER = """\
# GENERATED by `python -m compose_api.registry.catalog` from the vivarium-collective catalog. Do not edit by hand:
# to raise an entry above `listed`, add it to manifest.yaml with its evidence, which takes precedence over this file.
"""


class CatalogModule(BaseModel):
    name: str
    source: str
    ref: str = "main"
    package: str


def fetch_modules(client: httpx.Client) -> list[CatalogModule]:
    response = client.get(CATALOG_URL)
    response.raise_for_status()
    return [CatalogModule.model_validate(m) for m in response.json()]


def resolve_commit(client: httpx.Client, module: CatalogModule) -> str:
    repo = module.source.removeprefix("https://github.com/").removesuffix(".git")
    response = client.get(
        f"https://api.github.com/repos/{repo}/commits/{module.ref}",
        headers={"Accept": "application/vnd.github.sha"},
    )
    response.raise_for_status()
    return response.text.strip()


def build_entries(
    modules: list[CatalogModule], commits: dict[str, str], previous: dict[str, RegistryEntry], today: datetime.date
) -> list[RegistryEntry]:
    """An entry per module, pinned to `commits[name]`; an unchanged pin keeps its previous entry verbatim."""
    entries = []
    for module in sorted(modules, key=lambda m: m.name):
        commit = commits[module.name]
        earlier = previous.get(module.name)
        if earlier is not None and earlier.commit == commit:
            entries.append(earlier)
            continue
        entries.append(
            RegistryEntry(
                id=module.name,
                package=module.name,
                source=module.source,
                commit=commit,
                module_roots=[module.package],
                level=CurationLevel.LISTED,
                evidence=[f"Discovered in viva-catalog; pinned to `{module.ref}` as of {today.isoformat()}."],
            )
        )
    return entries


def read_catalog(path: Path = CATALOG_PATH) -> dict[str, RegistryEntry]:
    if not path.exists():
        return {}
    data: dict[str, Any] = yaml.safe_load(path.read_text()) or {}
    return {e.id: e for e in (RegistryEntry.model_validate(raw) for raw in data.get("entries", []))}


def write_catalog(entries: list[RegistryEntry], path: Path = CATALOG_PATH) -> None:
    body = {"entries": [e.model_dump(mode="json", exclude_none=True, exclude_defaults=True) for e in entries]}
    path.write_text(_HEADER + yaml.safe_dump(body, sort_keys=False, width=120))


def main() -> int:
    token = os.environ.get("GITHUB_TOKEN")
    headers = {"Authorization": f"Bearer {token}"} if token else {}
    with httpx.Client(headers=headers, timeout=30, follow_redirects=True) as client:
        modules = fetch_modules(client)
        commits = {m.name: resolve_commit(client, m) for m in modules}
    previous = read_catalog()
    entries = build_entries(modules, commits, previous, datetime.datetime.now(tz=datetime.UTC).date())
    write_catalog(entries)

    current = {e.id for e in entries}
    added = sorted(current - previous.keys())
    removed = sorted(previous.keys() - current)
    moved = sorted(e.id for e in entries if e.id in previous and previous[e.id].commit != e.commit)
    print(f"{len(entries)} catalog entries; added {added}, re-pinned {moved}, removed {removed}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
