import createClient, { type Client, type Middleware } from 'openapi-fetch'
import type { components, paths } from '~/api/schema'

export type Schemas = components['schemas']
export type SimulationSummary = Schemas['SimulationSummary']
export type SimulationDetail = Schemas['SimulationDetail']
export type HpcRun = Schemas['HpcRun']
export type RunEvent = Schemas['RunEvent']
export type SpanTree = Schemas['SpanTree']
export type Dataset = Schemas['Dataset']

let client: Client<paths> | null = null

const auth: Middleware = {
  async onRequest({ request }) {
    const token = await accessToken()
    if (token) request.headers.set('Authorization', `Bearer ${token}`)
    return request
  },
  async onResponse({ request, response }) {
    if (response.status === 401 && request.headers.has('Authorization')) {
      authState().rejected = 'The API did not accept your sign-in token, so requests are now anonymous. '
        + 'Sign out and in again; if this persists, the login is configured for a different API audience.'
    }
    return response
  }
}

/** Typed client for the compose-api spec (app/api/schema.d.ts, generated by `npm run types`). */
export function useApi(): Client<paths> {
  if (!client) {
    client = createClient<paths>({ baseUrl: useRuntimeConfig().public.apiBase })
    client.use(auth)
  }
  return client
}

/** An absolute URL for an API path, for links and downloads. */
export function apiUrl(path: string, query?: Record<string, string | number>): string {
  const base = useRuntimeConfig().public.apiBase
  const qs = query ? `?${new URLSearchParams(Object.entries(query).map(([k, v]) => [k, String(v)]))}` : ''
  return `${base}${path}${qs}`
}

export interface Violation {
  document: string
  address: string
  reason: string
  always_rejected?: boolean
}

/** A readable message from a FastAPI error body: a string, a {message, violations} rejection, or a 422 list. */
export function errorMessage(error: unknown, fallback = 'Request failed'): string {
  const detail = (error as { detail?: unknown } | undefined)?.detail
  if (typeof detail === 'string') return detail
  if (Array.isArray(detail)) {
    return detail.map((d: { loc?: unknown[], msg?: string }) => `${(d.loc ?? []).join('.')}: ${d.msg}`).join('; ')
  }
  if (detail && typeof detail === 'object' && 'message' in detail) return String(detail.message)
  return fallback
}

export function errorViolations(error: unknown): Violation[] {
  const detail = (error as { detail?: { violations?: Violation[] } } | undefined)?.detail
  return detail && typeof detail === 'object' && Array.isArray(detail.violations) ? detail.violations : []
}

/**
 * Save an API file. Anonymous callers follow a plain link; a signed-in caller fetches with the token, since a link
 * cannot carry the Authorization header (and a private simulation's files will need it).
 */
export async function downloadFile(path: string, query: Record<string, string | number>, filename: string) {
  const url = apiUrl(path, query)
  const token = await accessToken()
  const a = document.createElement('a')
  a.download = filename
  if (!token) {
    a.href = url
    a.click()
    return
  }
  const response = await fetch(url, { headers: { Authorization: `Bearer ${token}` } })
  if (!response.ok) throw new Error(`Download failed (${response.status})`)
  const blobUrl = URL.createObjectURL(await response.blob())
  a.href = blobUrl
  a.click()
  setTimeout(() => URL.revokeObjectURL(blobUrl), 10_000)
}

/** A `fetch` that adds the caller's token: for loaders (zarrita, viewers) that fetch API URLs themselves. */
export const authFetch: typeof fetch = async (input, init) => {
  const token = await accessToken()
  if (!token) return fetch(input, init)
  const headers = new Headers(init?.headers)
  headers.set('Authorization', `Bearer ${token}`)
  return fetch(input, { ...init, headers })
}

/** Where the files of a directory dataset (a zarr store) are served: append `/<path inside it>`. */
export function datasetFilesUrl(id: string): string {
  return apiUrl(`/datasets/${id}/files`)
}

/** Fetch a file's body with the caller's token, for inline previews. */
export async function fetchContent(path: string): Promise<Response> {
  const token = await accessToken()
  return fetch(apiUrl(path), token ? { headers: { Authorization: `Bearer ${token}` } } : undefined)
}
