# Use the official Python image from the Docker Hub
FROM python:3.14.3-slim-bookworm AS base

ARG APP_GID=10000
ARG APP_UID=16997

RUN apt-get update && \
    apt-get install -y --no-install-recommends \
    openssh-client libexpat1 && \
    rm -rf /var/lib/apt/lists/*

# Set environment variables
ENV PYTHONUNBUFFERED=1

COPY --from=ghcr.io/astral-sh/uv:latest /uv /bin/uv

# create user/group
RUN groupadd -g $APP_GID appgroup && \
    useradd -m -u $APP_UID -g $APP_GID appuser
USER appuser

# Change the working directory to the `app` directory
WORKDIR /app

# Copy the lockfile and `pyproject.toml` into the image
COPY --chown=appuser:appgroup uv.lock /app/uv.lock
COPY --chown=appuser:appgroup pyproject.toml /app/pyproject.toml

# Install dependencies
RUN uv sync --frozen --no-install-project

# Copy the project into the image
COPY --chown=appuser:appgroup . /app

# Sync the project
RUN uv sync --frozen

# Declare the volume for local cache storage
VOLUME ["/app/scratch"]

# Expose the port FastAPI will run on
EXPOSE 8000

ENV APP_DIR=/app/app
ENV ASSETS_DIR=/app/assets

# Command to run the application
CMD ["/bin/bash", "-c", "source .venv/bin/activate && uvicorn compose_api.api.main:app --host 0.0.0.0 --port 8000"]
