"""Generic Container Column

Revision ID: eb3903fb35a7
Revises: 93d2f0c0c00f
Create Date: 2026-05-05 12:03:14.277997

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'eb3903fb35a7'
down_revision: Union[str, Sequence[str], None] = '93d2f0c0c00f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    container_engine_enum = sa.Enum('DOCKER', 'APPTAINER', name='containerengine')
    container_engine_enum.create(op.get_bind())
    op.alter_column('simulator','singularity_def', new_column_name='container_def')
    op.alter_column('simulator', 'singularity_def_hash', new_column_name='container_def_hash')
    op.add_column('simulator', sa.Column('container_engine', container_engine_enum, nullable=True))
    op.execute("UPDATE simulator SET container_engine='APPTAINER'")
    op.alter_column('simulator', 'container_engine', nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('simulator', 'container_def', new_column_name='singularity_def')
    op.alter_column('simulator', 'container_def_hash', new_column_name='singularity_def_hash')
    op.drop_column('simulator', 'container_engine')
    sa.Enum(name='containerengine').drop(op.get_bind())
    # ### end Alembic commands ###
