---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: ghcr-secret
  namespace: compose-api-rke
spec:
  encryptedData:
    .dockerconfigjson: AgCjBaIbIJlBAQg2PFrqNFgL740v/DBf+9pbfztlCqJIhdPjKkRiSKiQQhlhzMfvaNW93CMLJdfv5ERz8cdfP/toGJGyETulsY8sAWt48GM5I6WsXJ7/SKkOy/StIJboh4gMK/wRQsvOhSou5W2dqMNxspNksnEbKsZ9KyTcwUeAW1I3esBCDolFcvf2/DRkC+oGVNTrN1lRXodewbKT/2Wn1wJL024nmxuzyak38fouDuN4FgnzNZw0X/boGak5dbJ9WH2CDmoD8Bl+jWKTb1yUdQzfLseYYUrxb2fGGD4SpfrxY/4McIxJ+2IgWH3aEEtmShrZYb5/uiaCnLrI3Ws8m3nNBFiI8oB+EfVGMI1lniUYvAxRdqeu7w45p6AKe8oV0NcdCPUQmAu/i+6YLDdH96fH8LiUNcan2QYrZHZHjjFPh43XML3gLfdGH6BBd/r2jxgcoOjrx/ymrEsVs/SGIf8s5y463gKHDjJNPy7n8MM2JBDkooxnQrzHDrjriM8KiL5h17mn9UyNJHRAq+/mV9LD20+4KZHf+BglsCRjxP5yR3QH8NpriW4fonYUBrneFvVtOe/O64IbA+fTA9Pg1HToCQUYJam10rgH0Y4ZcwQXF/zsq27EZmPHB7HyY0GmwzUtjL2IyKAqjgCVUsceEbkyHcUDwXzM13gz/ccbLyAc+bksxTz/NOqIV9kTGt+LgXXRhMZur+YBkwgbeAepOwyGBv4m3TZ3qC4mY48iN0elBPYGyMxsm2/LxvBqwJNpGCNcggAMtS3fNSxcacHojP8dkIGWPDLkQuSNnZMw+lJwxf6zIO0+Ufznn5cPkVJQVwa40poHStulWayDEoVl0YyNTgd+eD4QO1oaLZXKA8Qg4FEQzdjf7FMSMTtrGx/JBbMEi1bFzzlHL/oDTmfJQpFkNZdCmjPWJp0lEyI6SuFdmJVM7fvaT8ro9vjZmNMp/otka7FgJXZUt8RS3ZHS
  template:
    metadata:
      creationTimestamp: null
      name: ghcr-secret
      namespace: compose-api-rke
    type: kubernetes.io/dockerconfigjson
